name: svampkompass
description: "En kompass som visar vägen hem och till sparade svampställen."
publish_to: 'none'

version: 1.0.2+2003

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  flutter_compass: ^0.8.1
  shared_preferences: ^2.5.3
  geomag: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#2C5B3A"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"